name: Build Firmware

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@main
    - name: Build
      run: |
        sudo apt update
        sudo apt install -y build-essential
        ./build.sh
